/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankatm;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author shahe
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ImageIcon icon;
        icon = new ImageIcon("bank.png");
        this.setIconImage(icon.getImage());
        this.setTitle("BANK MANAGEMENT");
        
        
        clerkuser.setSelected(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account_id = new javax.swing.JTextField();
        userpassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clerkuser = new javax.swing.JRadioButton();
        customeruser = new javax.swing.JRadioButton();
        loginbutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account Id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        clerkuser.setBackground(new java.awt.Color(34, 39, 46));
        clerkuser.setForeground(new java.awt.Color(255, 255, 255));
        clerkuser.setText("Clerk");
        clerkuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkuserActionPerformed(evt);
            }
        });

        customeruser.setBackground(new java.awt.Color(34, 39, 46));
        customeruser.setForeground(new java.awt.Color(255, 255, 255));
        customeruser.setText("Customer");
        customeruser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customeruserMouseClicked(evt);
            }
        });
        customeruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeruserActionPerformed(evt);
            }
        });

        loginbutton.setBackground(new java.awt.Color(153, 153, 153));
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        resetbutton.setBackground(new java.awt.Color(153, 153, 153));
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetbutton)
                        .addGap(18, 18, 18)
                        .addComponent(loginbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customeruser)
                        .addGap(18, 18, 18)
                        .addComponent(clerkuser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account_id, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(account_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clerkuser)
                    .addComponent(customeruser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbutton)
                    .addComponent(resetbutton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customeruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeruserActionPerformed
        // TODO add your handling code here:
        if(customeruser.isSelected()){
            clerkuser.setSelected(false);
        }
    }//GEN-LAST:event_customeruserActionPerformed

    private void customeruserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customeruserMouseClicked

    }//GEN-LAST:event_customeruserMouseClicked

    private void clerkuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkuserActionPerformed
        // TODO add your handling code here:
        
        if(clerkuser.isSelected()){
            customeruser.setSelected(false);
        }
    }//GEN-LAST:event_clerkuserActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        account_id.setText("");
        userpassword.setText("");
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        Home h1 = new Home();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String user_id = account_id.getText();
        String password = userpassword.getText();
        String Query = null;
        if(customeruser.isSelected()){
            Query = "SELECT * FROM `normauser` where `user_id` =? AND `password` =?";
            try{
                ps = myconnection.getConnection().prepareStatement(Query);
                ps.setString(1, user_id);
                ps.setString(2, password);
                rs = ps.executeQuery();
                if(rs.next()){
                    String accountType = rs.getString("account_type");
                    h1.get_account_type(accountType);
                    h1.get_user_id(rs.getString("user_id"));
                    JOptionPane.showMessageDialog(null, "You are now logged in");
                    h1.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Account id or password is incorrent");
                }
            }catch(SQLException ex){
                System.out.println(ex);
            }finally{
                try{
                    ps.close();
                    rs.close();
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
        else if(!clerkuser.isSelected()){
        } else {
            Query = "SELECT * FROM `clerk` where `clerk_id` =? AND `password`=?";
            h1.get_account_type("clerk");
            try{
                ps = myconnection.getConnection().prepareStatement(Query);
                ps.setString(1, user_id);
                ps.setString(2, password);
                rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "You are now logged in");
                    h1.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Account Id or Password is incorrect");
                }
            }catch(SQLException ex){
                System.out.println(ex);
            }finally{
                try{
                    ps.close();
                    rs.close();
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_id;
    private javax.swing.JRadioButton clerkuser;
    private javax.swing.JRadioButton customeruser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField userpassword;
    // End of variables declaration//GEN-END:variables
}
